/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    id("org.xbib.gradle.plugin.jflex") version "3.0.2"
    id("cup.gradle.cup-gradle-plugin") version "2.0"
    kotlin("jvm") version "2.2.0"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation(libs.net.sourceforge.argparse4j)
    implementation(libs.jackson.core.jackson.databind)
    implementation(libs.jackson.module.parameter.names)
    implementation(libs.java.cup.runtime)
    implementation(libs.de.jflex)
    implementation(libs.kotlin.stdlib)
    implementation(libs.net.sf.proguard.proguard.base)
    testImplementation(libs.junit.junit)
}

group = "chocopy"
version = "2.0-SNAPSHOT"
description = "chocopy"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

jflex {
    rootDirectory = rootDir
}

cup {
    setArgs("-package", "chocopy.lexical", "-parser", "ChocoPyParser", "-symbols", "ChocoPyTokens", "-locations")
}

sourceSets {
    main {
        jflex {
            srcDir("src/main/jflex")
        }
    }
}

